crop_thresh: 0.5
kpt_thresh: 0.2
visual: True
warmup_frame: 50

MOT:
  model_dir: output_inference/mot_ppyoloe_l_36e_pipeline
  tracker_config: deploy/pipeline/config/tracker_config.yml
  batch_size: 1
  enable: False

KPT:
  model_dir: output_inference/dark_hrnet_w32_256x192
  batch_size: 8

SKELETON_ACTION:
  model_dir: output_inference/output_inference/STGCN
  batch_size: 1
  max_frames: 50
  display_frames: 80
  coord_size: [384, 512]
  enable: True

  #/home/aistudio/work/paddle-video6/output_inference/STGCN